# Config. do Gateway
server:
  port: 8090
# Config. do Eureka Server
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
# Config. do Spring Cloud
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      routes:
        - id: ms-bills
          uri: lb://ms-bills
          predicates:
            - Path=/api/v1/**
          filters:
            - StripPrefix=2
        - id: ms-users
          uri: lb://ms-users
          predicates:
            - Path=/users/**
      default-filters:
        - TokenRelay
        - LogFilter

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/avaliacao
        registration:
          keycloak-registration:
            provider: keycloak
            client-id: ms-gateway
            client-secret: pv7lVbz1Wb44fq3qxaiOgcfe3ObV0wCQ
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
            scope:
              - openid
management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, metrics, mappings
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.http: DEBUG
    org.springframework.web: DEBUG